[package]
name = "howmanysmall/uibenchmarks"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Helium = "howmanysmall/helium@1.1.3"
React = "core-packages/react@17.0.1-rc.19"
ReactReconciler = "core-packages/react-reconciler@17.0.1-rc.19"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
ReactTree = "howmanysmall/react-tree@1.0.0"
Roact = "roblox/roact@1.4.4"
HowRoactHooked = "howmanysmall/roact-hooked-luau@0.1.0"
RoactHooks = "kampfkarren/roact-hooks@0.5.1"

[place]
shared-packages = "game:GetService(\"ReplicatedStorage\").Packages"
